python findPeaks.py 10.0.csv
python findPeaks.py 12.6.csv
python findPeaks.py 2.6.csv
python findPeaks.py 5.3.csv
python findPeaks.py 7.8.csv
python findPeaks.py 10.1.csv
python findPeaks.py 12.7.csv
python findPeaks.py 2.7.csv
python findPeaks.py 5.4.csv
python findPeaks.py 7.9.csv
python findPeaks.py 10.2.csv
python findPeaks.py 12.8.csv
python findPeaks.py 2.8.csv
python findPeaks.py 5.5.csv
python findPeaks.py 8.0.csv
python findPeaks.py 10.3.csv
python findPeaks.py 12.9.csv
python findPeaks.py 2.9.csv
python findPeaks.py 5.6.csv
python findPeaks.py 8.1.csv
python findPeaks.py 10.4.csv
python findPeaks.py 13.0.csv
python findPeaks.py 3.0.csv
python findPeaks.py 5.7.csv
python findPeaks.py 8.2.csv
python findPeaks.py 10.5.csv
python findPeaks.py 13.1.csv
python findPeaks.py 3.1.csv
python findPeaks.py 5.8.csv
python findPeaks.py 8.3.csv
python findPeaks.py 10.6.csv
python findPeaks.py 13.2.csv
python findPeaks.py 3.2.csv
python findPeaks.py 5.9.csv
python findPeaks.py 8.4.csv
python findPeaks.py 10.7.csv
python findPeaks.py 13.3.csv
python findPeaks.py 3.3.csv
python findPeaks.py 5.0.csv
python findPeaks.py 8.5.csv
python findPeaks.py 10.8.csv
python findPeaks.py 13.4.csv
python findPeaks.py 3.4.csv
python findPeaks.py 6.1.csv
python findPeaks.py 8.6.csv
python findPeaks.py 10.9.csv
python findPeaks.py 13.5.csv
python findPeaks.py 3.5.csv
python findPeaks.py 6.2.csv
python findPeaks.py 8.7.csv
python findPeaks.py 11.0.csv
python findPeaks.py 13.6.csv
python findPeaks.py 3.6.csv
python findPeaks.py 6.3.csv
python findPeaks.py 8.8.csv
python findPeaks.py 11.1.csv
python findPeaks.py 13.7.csv
python findPeaks.py 3.7.csv
python findPeaks.py 6.4.csv
python findPeaks.py 8.9.csv
python findPeaks.py 11.2.csv
python findPeaks.py 13.8.csv
python findPeaks.py 3.8.csv
python findPeaks.py 6.5.csv
python findPeaks.py 9.0.csv
python findPeaks.py 11.3.csv
python findPeaks.py 13.9.csv
python findPeaks.py 3.9.csv
python findPeaks.py 6.6.csv
python findPeaks.py 9.1.csv
python findPeaks.py 11.4.csv
python findPeaks.py 14.0.csv
python findPeaks.py 4.0.csv
python findPeaks.py 6.7.csv
python findPeaks.py 9.2.csv
python findPeaks.py 11.5.csv
python findPeaks.py 14.1.csv
python findPeaks.py 4.1.csv
python findPeaks.py 6.8.csv
python findPeaks.py 9.3.csv
python findPeaks.py 11.6.csv
python findPeaks.py 14.2.csv
python findPeaks.py 4.2.csv
python findPeaks.py 6.9.csv
python findPeaks.py 9.4.csv
python findPeaks.py 11.7.csv
python findPeaks.py 14.3.csv
python findPeaks.py 4.3.csv
python findPeaks.py 6.0.csv
python findPeaks.py 9.5.csv
python findPeaks.py 11.8.csv
python findPeaks.py 14.4.csv
python findPeaks.py 4.4.csv
python findPeaks.py 7.0.csv
python findPeaks.py 9.6.csv
python findPeaks.py 11.9.csv
python findPeaks.py 14.5.csv
python findPeaks.py 4.5.csv
python findPeaks.py 7.1.csv
python findPeaks.py 9.7.csv
python findPeaks.py 12.0.csv
python findPeaks.py 14.6.csv
python findPeaks.py 4.6.csv
python findPeaks.py 7.2.csv
python findPeaks.py 9.8.csv
python findPeaks.py 12.1.csv
python findPeaks.py 14.7.csv
python findPeaks.py 4.7.csv
python findPeaks.py 7.3.csv
python findPeaks.py 12.2.csv
python findPeaks.py 14.8.csv
python findPeaks.py 4.8.csv
python findPeaks.py 7.4.csv
python findPeaks.py 12.3.csv
python findPeaks.py 14.9.csv
python findPeaks.py 12.4.csv
python findPeaks.py 15.0.csv
python findPeaks.py 5.1.csv
python findPeaks.py 7.6.csv
python findPeaks.py 12.5.csv
python findPeaks.py 2.5.csv
python findPeaks.py 5.2.csv
python findPeaks.py 7.7.csv
