python findPeaks.py 1-0.csv
python findPeaks.py 3-2.csv
python findPeaks.py 4-95.csv
python findPeaks.py 6-85.csv
python findPeaks.py 8-45.csv
python findPeaks.py 1-55.csv
python findPeaks.py 3-25.csv
python findPeaks.py 4.csv
python findPeaks.py 6-9.csv
python findPeaks.py 8-5.csv
python findPeaks.py 1-5.csv
python findPeaks.py 3-3.csv
python findPeaks.py 5-05.csv
python findPeaks.py 6-95.csv
python findPeaks.py 8-55.csv
python findPeaks.py 1-6.csv
python findPeaks.py 3-35.csv
python findPeaks.py 5-1.csv
python findPeaks.py 6.05.csv
python findPeaks.py 8-6.csv
python findPeaks.py 1-65.csv
python findPeaks.py 3-4.csv
python findPeaks.py 5-15.csv
python findPeaks.py 6.3.csv
python findPeaks.py 8-65.csv
python findPeaks.py 1-7.csv
python findPeaks.py 3-45.csv
python findPeaks.py 5-2.csv
python findPeaks.py 6.35.csv
python findPeaks.py 8-7.csv
python findPeaks.py 1-75.csv
python findPeaks.py 3-5.csv
python findPeaks.py 5-25.csv
python findPeaks.py 6.csv
python findPeaks.py 8-75.csv
python findPeaks.py 1-8.csv
python findPeaks.py 3-55.csv
python findPeaks.py 5-3.csv
python findPeaks.py 7-05.csv
python findPeaks.py 8-8.csv
python findPeaks.py 1-85.csv
python findPeaks.py 3-6.csv
python findPeaks.py 5-35.csv
python findPeaks.py 7-1.csv
python findPeaks.py 8-85.csv
python findPeaks.py 1-9.csv
python findPeaks.py 3-65.csv
python findPeaks.py 5-4.csv
python findPeaks.py 7-15.csv
python findPeaks.py 8-9.csv
python findPeaks.py 1-95.csv
python findPeaks.py 3-7.csv
python findPeaks.py 5-45.csv
python findPeaks.py 7-2.csv
python findPeaks.py 8-95.csv
python findPeaks.py 10.csv
python findPeaks.py 3-75.csv
python findPeaks.py 5-5.csv
python findPeaks.py 7-25.csv
python findPeaks.py 8.csv
python findPeaks.py 2-05.csv
python findPeaks.py 3-8.csv
python findPeaks.py 5-55.csv
python findPeaks.py 7-3.csv
python findPeaks.py 9-05.csv
python findPeaks.py 2-1.csv
python findPeaks.py 3-85.csv
python findPeaks.py 5-6.csv
python findPeaks.py 7-35.csv
python findPeaks.py 9-1.csv
python findPeaks.py 2-15.csv
python findPeaks.py 3-9.csv
python findPeaks.py 5-65.csv
python findPeaks.py 7-4.csv
python findPeaks.py 9-15.csv
python findPeaks.py 2-2.csv
python findPeaks.py 3-95.csv
python findPeaks.py 5-7.csv
python findPeaks.py 7-45.csv
python findPeaks.py 9-2.csv
python findPeaks.py 2-25.csv
python findPeaks.py 3.csv
python findPeaks.py 5-75.csv
python findPeaks.py 7-5.csv
python findPeaks.py 9-25.csv
python findPeaks.py 2-3.csv
python findPeaks.py 4-05.csv
python findPeaks.py 5-8.csv
python findPeaks.py 7-55.csv
python findPeaks.py 9-3.csv
python findPeaks.py 2-35.csv
python findPeaks.py 4-1.csv
python findPeaks.py 5-85.csv
python findPeaks.py 7-6.csv
python findPeaks.py 9-35.csv
python findPeaks.py 2-4.csv
python findPeaks.py 4-15.csv
python findPeaks.py 5-9.csv
python findPeaks.py 7-65.csv
python findPeaks.py 9-4.csv
python findPeaks.py 2-45.csv
python findPeaks.py 4-2.csv
python findPeaks.py 5-95.csv
python findPeaks.py 7-7.csv
python findPeaks.py 9-45.csv
python findPeaks.py 2-5.csv
python findPeaks.py 4-25.csv
python findPeaks.py 5.csv
python findPeaks.py 7-75.csv
python findPeaks.py 9-5.csv
python findPeaks.py 2-55.csv
python findPeaks.py 4-3.csv
python findPeaks.py 6-1.csv
python findPeaks.py 7-8.csv
python findPeaks.py 9-55.csv
python findPeaks.py 2-6.csv
python findPeaks.py 4-35.csv
python findPeaks.py 6-15.csv
python findPeaks.py 7-85.csv
python findPeaks.py 9-6.csv
python findPeaks.py 2-65.csv
python findPeaks.py 4-4.csv
python findPeaks.py 6-2.csv
python findPeaks.py 7-9.csv
python findPeaks.py 9-65.csv
python findPeaks.py 2-7.csv
python findPeaks.py 4-45.csv
python findPeaks.py 6-25.csv
python findPeaks.py 7-95.csv
python findPeaks.py 9-7.csv
python findPeaks.py 2-75.csv
python findPeaks.py 4-5.csv
python findPeaks.py 6-4.csv
python findPeaks.py 7.csv
python findPeaks.py 9-75.csv
python findPeaks.py 2-8.csv
python findPeaks.py 4-55.csv
python findPeaks.py 6-45.csv
python findPeaks.py 8-05.csv
python findPeaks.py 9-8.csv
python findPeaks.py 2-85.csv
python findPeaks.py 4-6.csv
python findPeaks.py 6-5.csv
python findPeaks.py 8-1.csv
python findPeaks.py 9-85.csv
python findPeaks.py 2-9.csv
python findPeaks.py 4-65.csv
python findPeaks.py 6-55.csv
python findPeaks.py 8-15.csv
python findPeaks.py 9-9.csv
python findPeaks.py 2-95.csv
python findPeaks.py 4-7.csv
python findPeaks.py 6-6.csv
python findPeaks.py 8-2.csv
python findPeaks.py 9-95.csv
python findPeaks.py 2.csv
python findPeaks.py 4-75.csv
python findPeaks.py 6-65.csv
python findPeaks.py 8-25.csv
python findPeaks.py 9.csv
python findPeaks.py 3-05.csv
python findPeaks.py 4-8.csv
python findPeaks.py 6-7.csv
python findPeaks.py 8-3.csv
python findPeaks.py 3-1.csv
python findPeaks.py 4-85.csv
python findPeaks.py 6-75.csv
python findPeaks.py 8-35.csv
python findPeaks.py 3-15.csv
python findPeaks.py 4-9.csv
python findPeaks.py 6-8.csv
python findPeaks.py 8-4.csv
